# Generated by Django 4.0.1 on 2022-09-15 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialsheet',
            name='profit_center',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
