# Generated by Django 4.0.1 on 2022-09-15 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_stock', '0002_materialsheet_profit_center'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialsheet',
            name='rate',
            field=models.FloatField(null=True),
        ),
    ]
