# Generated by Django 4.0.1 on 2022-09-16 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_stock', '0003_materialsheet_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialsheet',
            name='currency',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
