# Generated by Django 4.0.1 on 2022-09-22 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_stock', '0004_alter_materialsheet_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialsheet',
            name='pmp_unit_div',
        ),
        migrations.RemoveField(
            model_name='materialsheet',
            name='pmp_unit_euro',
        ),
        migrations.RemoveField(
            model_name='materialsheet',
            name='ps_unit_div',
        ),
        migrations.RemoveField(
            model_name='materialsheet',
            name='ps_unit_euro',
        ),
        migrations.RemoveField(
            model_name='materialsheet',
            name='valuation_pmp_div',
        ),
        migrations.RemoveField(
            model_name='materialsheet',
            name='valuation_pmp_euro',
        ),
        migrations.RemoveField(
            model_name='materialsheet',
            name='valuation_ps_div',
        ),
        migrations.RemoveField(
            model_name='materialsheet',
            name='valuation_ps_euro',
        ),
    ]
