# Generated by Django 4.0.1 on 2022-09-22 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_stock', '0006_remove_materialsheet_price_basis'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialsheet',
            name='price_basis',
            field=models.FloatField(null=True),
        ),
    ]
