# Generated by Django 4.0.1 on 2022-11-08 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_stock', '0007_materialsheet_price_basis'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialsheet',
            name='returnable_stock',
            field=models.FloatField(null=True),
        ),
    ]
