# Generated by Django 4.0.1 on 2023-01-02 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_stock', '0008_materialsheet_returnable_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='materialsheet',
            old_name='rate',
            new_name='rate_budget',
        ),
        migrations.AddField(
            model_name='materialsheet',
            name='rate_last',
            field=models.FloatField(null=True),
        ),
    ]
