# Generated by Django 4.0.1 on 2023-01-02 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_stock', '0010_remove_materialsheet_rate_budget_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialsheet',
            name='rate_budget',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='materialsheet',
            name='rate_last',
            field=models.FloatField(null=True),
        ),
    ]
