# Generated by Django 4.0.1 on 2022-10-19 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofpast', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coois',
            name='date_actual_launch',
            field=models.DateField(null=True),
        ),
    ]
