# Generated by Django 4.0.1 on 2022-02-28 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasepast', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='week',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
