# Generated by Django 4.0.1 on 2022-02-28 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasepast', '0002_purchase_week_purchase_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='deletion_indicator',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='division',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='item_of_requisition',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='outline_agreement',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='principal_agmt_item',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='purchase_order',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='purchase_order_item',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='purchase_requisition',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='purchasing_group',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='release_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='requisition_date',
            field=models.DateField(null=True),
        ),
    ]
