# Generated by Django 4.0.1 on 2022-03-04 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasepast', '0004_purchase_transferring_division_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='transferring_division',
            field=models.IntegerField(null=True),
        ),
    ]
