# Generated by Django 4.0.1 on 2022-03-25 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasepast', '0006_alter_purchase_transferring_division'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='material',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='supplier',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
