# Generated by Django 4.0.1 on 2022-10-21 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasepast', '0008_purchase_base_price_purchase_qte_requested'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='valuation_price_euro',
            field=models.FloatField(null=True),
        ),
    ]
