# Generated by Django 4.0.1 on 2022-10-21 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasepast', '0009_purchase_valuation_price_euro'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='company',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='currency',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='rate',
            field=models.FloatField(null=True),
        ),
    ]
