# Generated by Django 4.0.1 on 2023-01-11 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasepast', '0010_purchase_company_purchase_currency_purchase_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='store',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
