# Generated by Django 4.0.6 on 2022-07-19 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SQ00',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('week', models.IntegerField()),
                ('inventory_doc', models.CharField(max_length=50, null=True)),
                ('material', models.CharField(max_length=50, null=True)),
                ('designation', models.CharField(max_length=50, null=True)),
                ('type', models.CharField(max_length=10, null=True)),
                ('unit', models.CharField(max_length=10, null=True)),
                ('division', models.IntegerField()),
                ('store', models.IntegerField(null=True)),
                ('supplier', models.CharField(max_length=50, null=True)),
                ('theoritical_quantity', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('entred_quantity', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('deviation', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('deviation_cost', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('dev', models.CharField(max_length=10, null=True)),
                ('date_catchment', models.DateField(null=True)),
                ('corrected_by', models.CharField(max_length=50, null=True)),
                ('catchment', models.CharField(max_length=50, null=True)),
                ('delete', models.CharField(max_length=10, null=True)),
                ('refecrence_inventory', models.CharField(max_length=50, null=True)),
                ('inventory_number', models.CharField(max_length=50, null=True)),
                ('Tys', models.IntegerField(null=True)),
            ],
        ),
    ]
