# Generated by Django 4.0.1 on 2022-08-09 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_accuracy', '0003_sq00_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='sq00',
            name='deviation_cost_euro',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='sq00',
            name='rate',
            field=models.FloatField(null=True),
        ),
    ]
