# Generated by Django 4.0.1 on 2022-08-12 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_accuracy', '0004_sq00_deviation_cost_euro_sq00_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='sq00',
            name='week_date_cpt',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='sq00',
            name='year_date_cpt',
            field=models.IntegerField(null=True),
        ),
    ]
