# Generated by Django 4.0.1 on 2022-03-01 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homekpi',
            name='kpi',
            field=models.CharField(max_length=100),
        ),
    ]
