# Generated by Django 4.0.1 on 2022-03-01 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_alter_homekpi_kpi'),
    ]

    operations = [
        migrations.AddField(
            model_name='homekpi',
            name='theme',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
