# Generated by Django 4.0.1 on 2022-03-01 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_homekpi_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='homekpi',
            name='col',
            field=models.IntegerField(null=True),
        ),
    ]
