# Generated by Django 4.0.1 on 2023-01-26 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_order_past', '0002_order_files_week_order_files_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_files',
            name='Qte',
            field=models.FloatField(null=True),
        ),
    ]
