# Generated by Django 4.0.1 on 2023-01-26 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_order_past', '0003_alter_order_files_qte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_files',
            name='Designation1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order_files',
            name='Designation2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order_files',
            name='Designation3',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order_files',
            name='Designation4',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order_files',
            name='Designation5',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
