# Generated by Django 4.0.1 on 2023-01-26 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_order_past', '0004_alter_order_files_designation1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_files',
            name='Remarque1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order_files',
            name='Remarque2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order_files',
            name='Remarque3',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
