# Generated by Django 4.0.1 on 2023-01-27 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_order_past', '0006_alter_order_files_past_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_files',
            name='Sort_March',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
