# Generated by Django 4.0.1 on 2023-01-27 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_order_past', '0007_alter_order_files_sort_march'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_files',
            name='ArticleClient',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order_files',
            name='ArticleInterne',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order_files',
            name='BF',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order_files',
            name='BL',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order_files',
            name='CPmt',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order_files',
            name='CtrPr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order_files',
            name='Designation_CP',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order_files',
            name='Destinataire',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order_files',
            name='Dev',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order_files',
            name='Div',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order_files',
            name='Ech_Clt',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order_files',
            name='Error_Bill_vs_Price',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order_files',
            name='Error_Routes',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order_files',
            name='Error_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order_files',
            name='GrI',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order_files',
            name='Incoterms2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order_files',
            name='Inctm',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order_files',
            name='Itin',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order_files',
            name='MSN',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order_files',
            name='Memo',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order_files',
            name='NonFact',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order_files',
            name='NoteEntete',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order_files',
            name='OTP',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order_files',
            name='OrgCm',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order_files',
            name='PointDechargement',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order_files',
            name='PosClt',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order_files',
            name='PosPrev',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order_files',
            name='PosSILOG',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order_files',
            name='PosteSAP',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order_files',
            name='Pri',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order_files',
            name='Program_responsible',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order_files',
            name='Rf',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order_files',
            name='SG',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order_files',
            name='SL',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order_files',
            name='Sort_March',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order_files',
            name='TyPo',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order_files',
            name='clientLivre',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order_files',
            name='design_centre_profit',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order_files',
            name='don_ordre',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order_files',
            name='n_CdeClient',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order_files',
            name='n_CdePrev',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order_files',
            name='n_CdeSAP',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order_files',
            name='n_CdeSILOG',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order_files',
            name='n_Contrat',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order_files',
            name='n_SerieDebut',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order_files',
            name='n_SerieFin',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
