# Generated by Django 4.0.1 on 2023-01-27 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_order_past', '0008_alter_order_files_articleclient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_files',
            name='Memo',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
