# Generated by Django 4.0.1 on 2023-01-27 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_order_past', '0009_alter_order_files_memo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_files',
            name='Remarque1',
        ),
        migrations.RemoveField(
            model_name='order_files',
            name='Remarque2',
        ),
        migrations.RemoveField(
            model_name='order_files',
            name='Remarque3',
        ),
    ]
