# Generated by Django 4.0.1 on 2023-01-27 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_order_past', '0010_remove_order_files_remarque1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_files',
            name='PointDechargement',
        ),
    ]
