# Generated by Django 4.0.1 on 2023-01-27 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_order_past', '0011_remove_order_files_pointdechargement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_files',
            name='Memo',
        ),
    ]
