# Generated by Django 4.0.1 on 2023-01-27 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_order_past', '0012_remove_order_files_memo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_files',
            name='Dtlivr_Ech',
            field=models.DateField(null=True),
        ),
    ]
