# Generated by Django 4.0.1 on 2023-01-30 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_order_past', '0013_alter_order_files_dtlivr_ech'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_past_per_cp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('week', models.IntegerField()),
                ('cp', models.CharField(max_length=30)),
                ('count', models.IntegerField(null=True)),
                ('price', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order_past_per_divsion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('week', models.IntegerField()),
                ('division', models.CharField(max_length=30)),
                ('count', models.IntegerField(null=True)),
                ('price', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order_past_per_errors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('week', models.IntegerField()),
                ('error', models.CharField(max_length=30)),
                ('count', models.IntegerField(null=True)),
                ('price', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order_past_per_organisme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('week', models.IntegerField()),
                ('organisme', models.CharField(max_length=30)),
                ('count', models.IntegerField(null=True)),
                ('price', models.FloatField(null=True)),
            ],
        ),
    ]
