# Generated by Django 4.0.1 on 2023-02-13 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_order_past', '0014_order_past_per_cp_order_past_per_divsion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_files',
            name='diff_date',
            field=models.FloatField(null=True),
        ),
    ]
