# Generated by Django 4.0.1 on 2022-02-22 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cogi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatment_status', models.CharField(max_length=100)),
                ('stock_movement_doc', models.CharField(max_length=100)),
                ('created_on', models.DateField()),
                ('time', models.TimeField()),
                ('error_date', models.DateField()),
                ('time_error', models.TimeField()),
                ('message_number', models.CharField(max_length=100)),
                ('movement_code', models.CharField(max_length=100)),
                ('error_text', models.CharField(max_length=200)),
                ('matrial', models.CharField(max_length=100)),
                ('division', models.CharField(max_length=100)),
                ('store', models.CharField(max_length=100)),
                ('order', models.CharField(max_length=100)),
                ('customer_order', models.CharField(max_length=100)),
                ('customer_order_item', models.CharField(max_length=100)),
                ('otp_element', models.CharField(max_length=100)),
                ('qty_unit_entered', models.CharField(max_length=100)),
            ],
        ),
    ]
