# Generated by Django 4.0.1 on 2022-02-22 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cogi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cogi',
            name='week',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='cogi',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
