# Generated by Django 4.0.1 on 2022-03-25 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cogi', '0003_alter_cogi_created_on_alter_cogi_customer_order_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cogi',
            old_name='matrial',
            new_name='material',
        ),
    ]
